Личный проект: истина где-то на сервере
htmlacademy-react/1237807-what-to-watch-5 pull request #12
Opened 2020-11-04 13:31 UTC by julia-marta

2020-11-04 13:36 UTC, julia-marta commented
Есть пара проблем:
1. В компоненте movie-page рендер сразу ломается, потому что не хватает данных для отрисовки табов (фильм приходит только позже, в дид маунт) - сейчас я поставила в рендере проверку, что если есть film.id (то есть данные полностью загружены), тогда рисуем, но это костыль. Как это можно решить?
2. Для плеера я получаю фильм в хоке withVideo (потому что он уже классовый и мне показалось, что это удобнее, чем заводить состояние плееру), но из-за этого фильм приходит в компонент player не сразу (опять же, потому что рендер выполняется ДО дид маунта), поэтому консоль ругается, что не приходят заявленные обязательными пропсы. Может, не надо передавать фильм из хока в компонент? Тогда подскажи, где его лучше получать.

Спасибо!

2020-11-04 19:13 UTC, balesniy commented
Это не костыли, в реальной жизни покажем загрузчик . И с плеером и с фильмом. Я уже завтра смогу все внимательно посмотреть14:37, 4 ноября 2020 г., Julia Marta <notifications@github.com>:
Есть пара проблем:

В компоненте movie-page рендер сразу ломается, потому что не хватает данных для отрисовки табов (фильм приходит только позже, в дид маунт) - сейчас я поставила в рендере проверку, что если есть film.id (то есть данные полностью загружены), тогда рисуем, но это костыль. Как это можно решить?
Для плеера я получаю фильм в хоке withVideo (потому что он уже классовый и мне показалось, что это удобнее, чем заводить состояние плееру), но из-за этого фильм приходит в компонент player не сразу (опять же, потому что рендер выполняется ДО дид маунта), поэтому консоль ругается, что не приходят заявленные обязательными пропсы. Может, не надо передавать фильм из хока в компонент? Тогда подскажи, где его лучше получать.

Спасибо!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

2020-11-05 17:44 UTC, balesniy requested changes

2020-11-05 17:44 UTC, balesniy commented on src/components/add-review/add-review.jsx
> +const api = createAPI(() => {});
апи у нас уже есть в мидлваре

2020-11-05 17:44 UTC, balesniy commented on src/components/add-review/add-review.jsx
> +    this.state = {
состояние просят выносить в хоки

2020-11-05 17:44 UTC, balesniy commented on src/components/add-review/add-review.jsx
> +    api.get(`${APIRoute.FILMS}/${id}`)
этот код нужно оформить в действие

2020-11-05 17:44 UTC, balesniy commented on src/components/add-review/add-review.jsx
> +      throw error;
тут нужно показать сообщение

2020-11-05 17:44 UTC, balesniy commented on src/components/movie-page/movie-page.jsx
> +const api = createAPI(() => {});
и тут нужны экшены

2020-11-05 17:44 UTC, balesniy commented on src/components/movie-page/movie-page.jsx
> +    this.state = {
хок

2020-11-07 12:39 UTC, merged